server:
  port: 5000
spring:
  application:
    name: user-service-backend
  datasource:
    url: jdbc:mysql://localhost:3306/cs_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
